# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhello.proto\x12\x05myapp\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x8a\x02\n\x0fGreetingService\x12\x32\n\x05Hello\x12\x13.myapp.HelloRequest\x1a\x14.myapp.HelloResponse\x12@\n\x11HelloServerStream\x12\x13.myapp.HelloRequest\x1a\x14.myapp.HelloResponse0\x01\x12@\n\x11HelloClientStream\x12\x13.myapp.HelloRequest\x1a\x14.myapp.HelloResponse(\x01\x12?\n\x0eHelloBiStreams\x12\x13.myapp.HelloRequest\x1a\x14.myapp.HelloResponse(\x01\x30\x01\x42\nZ\x08pkg/grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010pkg/grpc'
  _globals['_HELLOREQUEST']._serialized_start=22
  _globals['_HELLOREQUEST']._serialized_end=50
  _globals['_HELLORESPONSE']._serialized_start=52
  _globals['_HELLORESPONSE']._serialized_end=84
  _globals['_GREETINGSERVICE']._serialized_start=87
  _globals['_GREETINGSERVICE']._serialized_end=353
# @@protoc_insertion_point(module_scope)
